{
 "title": "Garmin Stats",
 "time": { "from": "now-60d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "ActivityGPS",
    "label": "Activity with GPS",
    "query": {
     "query": "SHOW TAG VALUES FROM \"ActivityGPS\" WITH KEY = \"ActivitySelector\" WHERE $timeFilter"
    }
   },
   {
    "name": "TimeZone",
    "label": "Local Time Zone",
    "query": "Europe/London, Europe/Paris, Europe/Berlin, Europe/Madrid, Europe/Rome, Europe/Amsterdam, Europe/Brussels, Europe/Zurich, Europe/Stockholm, Europe/Warsaw, Europe/Budapest, Europe/Istanbul, Europe/Athens, Europe/Moscow, America/New_York, America/Chicago, America/Denver, America/Los_Angeles, America/Toronto, America/Vancouver, America/Mexico_City, America/Sao_Paulo, America/Buenos_Aires, America/Lima, America/Bogota, Africa/Johannesburg, Africa/Cairo, Africa/Nairobi, Africa/Lagos, Asia/Tokyo, Asia/Seoul, Asia/Shanghai, Asia/Singapore, Asia/Kolkata, Asia/Bangkok, Asia/Dubai, Asia/Hong_Kong, Asia/Kuala_Lumpur, Asia/Jakarta, Asia/Manila, Asia/Taipei, Asia/Karachi, Asia/Colombo, Asia/Ho_Chi_Minh, Australia/Sydney, Australia/Melbourne, Australia/Brisbane, Australia/Perth, Pacific/Auckland, Pacific/Honolulu"
   }
  ]
 },
 "panels": [
  { "title": "Strength training", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load - Back",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$tag_Primary_Muscle",
     "query": "SELECT sum(\"Volume\") FROM \"Strength_set\" WHERE $timeFilter GROUP BY time($__interval), \"Primary_Muscle\""
    }
   ]
  },
  {
   "title": "Evolution - back",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 1 },
   "targets": [
    {
     "alias": "average - $tag_Primary_Muscle",
     "query": "SELECT moving_average(sum(\"Volume\"), 4)\nFROM \"Strength_set\"\nWHERE time >= now() - 52w AND (\"Primary_Muscle\"::tag = 'back')\nGROUP BY time(1d), \"Primary_Muscle\""
    },
    {
     "alias": "$tag_Primary_Muscle",
     "query": "SELECT sum(\"Volume\")\nFROM \"Strength_set\"\nWHERE $timeFilter AND (\"Primary_Muscle\"::tag = 'back')\nGROUP BY time($__interval), \"Primary_Muscle\""
    }
   ]
  },
  {
   "title": "Load - Triceps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "$tag_Primary_Muscle",
     "query": "SELECT sum(\"Volume\") FROM \"Strength_set\" WHERE $timeFilter GROUP BY time($__interval), \"Primary_Muscle\""
    }
   ]
  },
  {
   "title": "Evolution - triceps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 1 },
   "targets": [
    {
     "alias": "average - $tag_Primary_Muscle",
     "query": "SELECT moving_average(sum(\"Volume\"), 4)\nFROM \"Strength_set\"\nWHERE time >= now() - 52w AND (\"Primary_Muscle\"::tag = 'triceps')\nGROUP BY time(1d), \"Primary_Muscle\""
    },
    {
     "alias": "$tag_Primary_Muscle",
     "query": "SELECT sum(\"Volume\")\nFROM \"Strength_set\"\nWHERE $timeFilter AND (\"Primary_Muscle\"::tag = 'triceps')\nGROUP BY time($__interval), \"Primary_Muscle\""
    }
   ]
  },
  {
   "title": "Load - Biceps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "$tag_Primary_Muscle",
     "query": "SELECT sum(\"Volume\") FROM \"Strength_set\" WHERE $timeFilter GROUP BY time($__interval), \"Primary_Muscle\""
    }
   ]
  },
  {
   "title": "Evolution - biceps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 9 },
   "targets": [
    {
     "alias": "average - $tag_Primary_Muscle",
     "query": "SELECT moving_average(sum(\"Volume\"), 4)\nFROM \"Strength_set\"\nWHERE time >= now() - 52w AND (\"Primary_Muscle\"::tag = 'biceps')\nGROUP BY time(1d), \"Primary_Muscle\""
    },
    {
     "alias": "$tag_Primary_Muscle",
     "query": "SELECT sum(\"Volume\")\nFROM \"Strength_set\"\nWHERE $timeFilter AND (\"Primary_Muscle\"::tag = 'biceps')\nGROUP BY time($__interval), \"Primary_Muscle\""
    }
   ]
  },
  {
   "title": "Load - Shoulders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "targets": [
    {
     "alias": "$tag_Primary_Muscle",
     "query": "SELECT sum(\"Volume\") FROM \"Strength_set\" WHERE $timeFilter GROUP BY time($__interval), \"Primary_Muscle\""
    }
   ]
  },
  {
   "title": "Evolution - shoulders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 9 },
   "targets": [
    {
     "alias": "average - $tag_Primary_Muscle",
     "query": "SELECT moving_average(sum(\"Volume\"), 4)\nFROM \"Strength_set\"\nWHERE time >= now() - 52w AND (\"Primary_Muscle\"::tag = 'shoulders')\nGROUP BY time(1d), \"Primary_Muscle\""
    },
    {
     "alias": "$tag_Primary_Muscle",
     "query": "SELECT sum(\"Volume\")\nFROM \"Strength_set\"\nWHERE $timeFilter AND (\"Primary_Muscle\"::tag = 'shoulders')\nGROUP BY time($__interval), \"Primary_Muscle\""
    }
   ]
  },
  {
   "title": "Load - Chest",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "$tag_Primary_Muscle",
     "query": "SELECT sum(\"Volume\") FROM \"Strength_set\" WHERE $timeFilter GROUP BY time($__interval), \"Primary_Muscle\""
    }
   ]
  },
  {
   "title": "Evolution - chest",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 17 },
   "targets": [
    {
     "alias": "average - $tag_Primary_Muscle",
     "query": "SELECT moving_average(sum(\"Volume\"), 4)\nFROM \"Strength_set\"\nWHERE time >= now() - 52w AND (\"Primary_Muscle\"::tag = 'chest')\nGROUP BY time(1d), \"Primary_Muscle\""
    },
    {
     "alias": "$tag_Primary_Muscle",
     "query": "SELECT sum(\"Volume\")\nFROM \"Strength_set\"\nWHERE $timeFilter AND (\"Primary_Muscle\"::tag = 'chest')\nGROUP BY time($__interval), \"Primary_Muscle\""
    }
   ]
  },
  {
   "title": "Heatmap - Muscle load",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 25 },
   "targets": [
    {
     "alias": "$tag_Primary_Muscle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "Strength_set",
     "query": "SELECT sum(\"Volume\") FROM \"Strength_set\" WHERE $timeFilter GROUP BY time($__interval), \"Primary_Muscle\"",
     "select": [
      [
       { "params": [ "Volume" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Detailed strength training",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 33 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "Strength_set",
     "query": "SELECT \"ActivityName\", \"Primary_Muscle\", \"Category\", \"Subcategory\", \"Repetitions\", \"Weight\", \"Volume\", \"Duration\"  FROM \"Strength_set\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "ActivityName" ], "type": "field" }
      ],
      [
       { "params": [ "Category" ], "type": "field" }
      ],
      [
       { "params": [ "Subcategory" ], "type": "field" }
      ],
      [
       { "params": [ "Repetitions" ], "type": "field" }
      ],
      [
       { "params": [ "Weight" ], "type": "field" }
      ],
      [
       { "params": [ "Duration" ], "type": "field" }
      ],
      [
       { "params": [ "Primary_Muscle" ], "type": "field" }
      ],
      [
       { "params": [ "Volume" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Intraday Health Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Sync ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1388 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "HeartRateIntraday",
       "select": [
        [
         { "params": [ "HeartRate" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Heart Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 21, "x": 3, "y": 1388 },
     "targets": [
      {
       "alias": "Heart Rate",
       "groupBy": [
        { "params": [ "2m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "HeartRateIntraday",
       "select": [
        [
         { "params": [ "HeartRate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Heart Rate Distribution",
     "type": "histogram",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1391 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Heart rate histogram",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "HeartRate_Intraday",
       "query": "select mean_value from (SELECT mean(\"HeartRate\") as mean_value FROM \"HeartRateIntraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value <= 96",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Heart rate histogram > 96",
       "measurement": "HeartRate_Intraday",
       "query": "select mean_value from (SELECT mean(\"HeartRate\") as mean_value FROM \"HeartRateIntraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value > 96",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Heart rate histogram < 60",
       "measurement": "HeartRate_Intraday",
       "query": "select mean_value from (SELECT mean(\"HeartRate\") as mean_value FROM \"HeartRateIntraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value < 60",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Heart rate histogram > 110",
       "measurement": "HeartRate_Intraday",
       "query": "select mean_value from (SELECT mean(\"HeartRate\") as mean_value FROM \"HeartRateIntraday\" WHERE $timeFilter GROUP BY time(1m) fill(null)) where mean_value > 110",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Today RHR",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1396 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DailyStats",
       "select": [
        [
         { "params": [ "restingHeartRate" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tz": "$TimeZone"
      }
     ]
    },
    {
     "title": "Stress",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1397 },
     "targets": [
      {
       "alias": "Stress",
       "measurement": "StressIntraday",
       "select": [
        [
         { "params": [ "stressLevel" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Body Battery",
       "measurement": "BodyBatteryIntraday",
       "select": [
        [
         { "params": [ "BodyBatteryLevel" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Today's Steps",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1401 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DailyStats",
       "select": [
        [
         { "params": [ "totalSteps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tz": "$TimeZone"
      }
     ]
    },
    {
     "title": "Steps Cumulative (24h)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1405 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Intraday Steps",
       "groupBy": [
        { "params": [ "15m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "StepsIntraday",
       "query": "SELECT moving_average(mean(\"value\"), 6) FROM \"HeartRate_Intraday\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "StepsCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Sleep Hours",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1407 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "Total Asleep",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "SleepSummary",
       "select": [
        [
         { "params": [ "sleepTimeSeconds" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tz": "$TimeZone"
      }
     ]
    },
    {
     "title": "High Stress Duration",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1413 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "Stress",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DailyStats",
       "select": [
        [
         { "params": [ "highStressDuration" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tz": "$TimeZone"
      }
     ]
    },
    {
     "title": "Steps Hourly (24h)",
     "type": "state-timeline",
     "gridPos": { "h": 3, "w": 21, "x": 3, "y": 1413 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Hourly Steps",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "StepsIntraday",
       "query": "SELECT moving_average(mean(\"value\"), 6) FROM \"HeartRate_Intraday\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "StepsCount" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tz": "$TimeZone"
      }
     ]
    },
    {
     "title": "Breathing Rates",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 21, "x": 3, "y": 1416 },
     "targets": [
      {
       "alias": "BR",
       "groupBy": [
        { "params": [ "2m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "BreathingRateIntraday",
       "select": [
        [
         { "params": [ "BreathingRate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Sleep",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1420 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "Deep",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "SleepSummary",
       "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "deepSleepSeconds" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tz": "$TimeZone"
      },
      {
       "alias": "Light",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "SleepSummary",
       "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "lightSleepSeconds" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tz": "$TimeZone"
      },
      {
       "alias": "REM",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "SleepSummary",
       "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "remSleepSeconds" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tz": "$TimeZone"
      },
      {
       "alias": "Awake",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "SleepSummary",
       "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "awakeSleepSeconds" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tz": "$TimeZone"
      }
     ]
    },
    {
     "title": "Sleep Movement Activity",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 21, "x": 3, "y": 1423 },
     "targets": [
      {
       "alias": "Sleeping Movement Activity",
       "measurement": "SleepIntraday",
       "select": [
        [
         { "params": [ "SleepMovementActivityLevel" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Today Activity",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1427 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "Sedentary",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DailyStats",
       "select": [
        [
         { "params": [ "sedentarySeconds" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tz": "$TimeZone"
      },
      {
       "alias": "Intense Activity",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DailyStats",
       "select": [
        [
         { "params": [ "vigorousIntensityMinutes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "* 60" ], "type": "math" }
        ]
       ],
       "tz": "$TimeZone"
      },
      {
       "alias": "Moderate Activity",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DailyStats",
       "select": [
        [
         { "params": [ "moderateIntensityMinutes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "* 60" ], "type": "math" }
        ]
       ],
       "tz": "$TimeZone"
      },
      {
       "alias": "Sleeping",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DailyStats",
       "select": [
        [
         { "params": [ "sleepingSeconds" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tz": "$TimeZone"
      }
     ]
    },
    {
     "title": "Sleep Intraday Stats",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 21, "x": 3, "y": 1430 },
     "targets": [
      {
       "alias": "Sleeping Heart Rate",
       "measurement": "SleepIntraday",
       "select": [
        [
         { "params": [ "heartRate" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "SpO2",
       "measurement": "SleepIntraday",
       "select": [
        [
         { "params": [ "spo2Reading" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "HRV",
       "measurement": "HRV_Intraday",
       "select": [
        [
         { "params": [ "hrvValue" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Sleep Stages",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 21, "x": 3, "y": 1439 },
     "targets": [
      {
       "alias": "Deep",
       "measurement": "SleepIntraday",
       "query": "SELECT \"SleepStageLevel\"+1 FROM \"SleepIntraday\" WHERE SleepStageLevel=0 AND $timeFilter",
       "select": [
        [
         { "params": [ "SleepStageLevel" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Light",
       "measurement": "SleepIntraday",
       "query": "SELECT \"SleepStageLevel\"+1 FROM \"SleepIntraday\" WHERE SleepStageLevel=1 AND $timeFilter",
       "select": [
        [
         { "params": [ "SleepStageLevel" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "REM",
       "measurement": "SleepIntraday",
       "query": "SELECT \"SleepStageLevel\"+1 FROM \"SleepIntraday\" WHERE SleepStageLevel=2 AND $timeFilter",
       "select": [
        [
         { "params": [ "SleepStageLevel" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "Awake",
       "measurement": "SleepIntraday",
       "query": "SELECT \"SleepStageLevel\"+1 FROM \"SleepIntraday\" WHERE SleepStageLevel=3 AND $timeFilter",
       "select": [
        [
         { "params": [ "SleepStageLevel" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Activity HR Zones (mean)",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1446 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "Zone 1",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ActivitySummary",
       "select": [
        [
         { "params": [ "hrTimeInZone_1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tz": "$TimeZone"
      },
      {
       "alias": "Zone 2",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ActivitySummary",
       "select": [
        [
         { "params": [ "hrTimeInZone_2" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tz": "$TimeZone"
      },
      {
       "alias": "Zone 3",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ActivitySummary",
       "select": [
        [
         { "params": [ "hrTimeInZone_3" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tz": "$TimeZone"
      },
      {
       "alias": "Zone 4",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ActivitySummary",
       "select": [
        [
         { "params": [ "hrTimeInZone_4" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tz": "$TimeZone"
      },
      {
       "alias": "Zone 5",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ActivitySummary",
       "select": [
        [
         { "params": [ "hrTimeInZone_5" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tz": "$TimeZone"
      }
     ]
    },
    {
     "title": "Activity Calories (mean)",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 5, "x": 5, "y": 1446 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "calories",
       "measurement": "ActivitySummary",
       "select": [
        [
         { "params": [ "calories" ], "type": "field" }
        ]
       ]
      },
      {
       "alias": "BMR calories",
       "measurement": "ActivitySummary",
       "select": [
        [
         { "params": [ "bmrCalories" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Activity HR difference (Max-Avg)",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 4, "x": 10, "y": 1446 },
     "targets": [
      {
       "alias": "avgHR",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ActivitySummary",
       "select": [
        [
         { "params": [ "averageHR" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tz": "$TimeZone"
      },
      {
       "alias": "maxHR",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ActivitySummary",
       "select": [
        [
         { "params": [ "maxHR" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tz": "$TimeZone"
      }
     ]
    },
    {
     "title": "Activity Distance",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 5, "x": 14, "y": 1446 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "targets": [
      {
       "alias": "Distance",
       "measurement": "ActivitySummary",
       "select": [
        [
         { "params": [ "distance" ], "type": "field" }
        ]
       ],
       "tz": "$TimeZone"
      }
     ]
    },
    {
     "title": "Activity Duration",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1446 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "Duration",
       "measurement": "ActivitySummary",
       "select": [
        [
         { "params": [ "elapsedDuration" ], "type": "field" }
        ]
       ],
       "tz": "$TimeZone"
      }
     ]
    }
   ]
  },
  { "title": "Recent Activities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "GPS Track by Velocity",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "alias": "lat",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Latitude" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "lon",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Longitude" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "HR",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "speed (Km/h)",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Speed" ], "type": "field" },
       { "params": [ "* 3.6" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPS Track by Heart Rate",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "alias": "lat",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Latitude" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "lon",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Longitude" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "HR",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "speed",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPS Track Heart Rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "HR",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPS Track Cadence",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Cadence",
     "measurement": "ActivityGPS",
     "query": "SELECT (1000/(\"Cadence\"* 60)) FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "Cadence" ], "type": "field" },
       { "params": [ "* 2" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean cadence",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ActivityGPS",
     "select": [
      [
       { "params": [ "Cadence" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 2" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Distance vs HR",
   "type": "trend",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "alias": "Distance",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "Distance" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "Heart Rate",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "Pace",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "Speed" ], "type": "field" },
       { "params": [ "* 3.6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "Duration",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "DurationSeconds" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    }
   ]
  },
  {
   "title": "Heart Rate vs Pace",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "alias": "Speed (Km/h)",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "Speed" ], "type": "field" },
       { "params": [ "* 3.6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "Heart Rate",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    }
   ]
  },
  {
   "title": "GPS Track pace",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "alias": "m/s",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Speed\" FROM \"ActivityGPS\" WHERE \"Speed\" > 0 AND  (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "Speed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    },
    {
     "alias": "Duration",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "DurationSeconds" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    }
   ]
  },
  {
   "title": "GPS Track Altitude",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Altitude",
     "measurement": "ActivityGPS",
     "query": "SELECT \"HeartRate\" FROM \"ActivityGPS\" WHERE (\"ActivitySelector\"::tag =~ /^$ActivityGPS$/)",
     "select": [
      [
       { "params": [ "Altitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ActivitySelector::tag", "operator": "=~", "value": "/^$ActivityGPS$/" }
     ]
    }
   ]
  },
  {
   "title": "Recent Activity",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Activity Type",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "activityType" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Duration",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "elapsedDuration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Max HR",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "maxHR" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Max Speed",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "maxSpeed" ], "type": "field" },
       { "params": [ "* 3.6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Distance",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Location",
     "measurement": "ActivitySummary",
     "query": "SELECT \"duration\" FROM \"Activity Records\" WHERE (\"ActivityName\" = 'Walk') AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "locationName" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityType::field", "operator": "!=", "value": "No Activity" }
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Activities",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 116 },
   "targets": [
    {
     "alias": "Activity Timeline",
     "measurement": "ActivitySummary",
     "select": [
      [
       { "params": [ "activityType" ], "type": "field" }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  { "title": "Long term visualization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Week at a Glance",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 121 },
   "targets": [
    {
     "alias": "Distance Covered",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "totalDistanceMeters" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Steps",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "totalSteps" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Total Sleep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sleepingSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "High Stress Duration",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "High Activity Duration",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highlyActiveSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Resting Heart Rate",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "restingHeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Avg SpO2",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "averageSpo2" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Body Battery Change",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bodyBatteryChargedValue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Daily Steps",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Steps",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "totalSteps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Daily Distance",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "alias": "Distance Covered",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "totalDistanceMeters" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Daily Calories",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "BMR Calories",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bmrKilocalories" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Activity Calories",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "activeKilocalories" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Daily avg health metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Avg SpO2",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "averageSpO2Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Avg HRV",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HRV_Intraday",
     "select": [
      [
       { "params": [ "hrvValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Avg Resting HR",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "restingHeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Daily avg health metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Avg Breathing Rate",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BreathingRateIntraday",
     "select": [
      [
       { "params": [ "BreathingRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Avg Stress",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StressIntraday",
     "select": [
      [
       { "params": [ "stressLevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Avg Sleeping Stress",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "avgSleepStress" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "VO2 Max",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "VO2 Max",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "VO2_Max",
     "select": [
      [
       { "params": [ "VO2_max_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Avg Activity over given duration",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Sedentary",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sedentarySeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Intense Activity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highlyActiveSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Fair Activity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "activeSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Sleeping",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sleepingSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Heatmap for GPS Activity (within selected time)",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 150 },
   "targets": [
    {
     "alias": "lat",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Latitude" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "lon",
     "measurement": "ActivityGPS",
     "query": "SELECT \"Latitude\",\"Longitude\" FROM \"ActivityGPS\" WHERE \"ActivitySelector\"::tag = \"20250413T084245UTC-Other-Lap3\" AND $timeFilter",
     "select": [
      [
       { "params": [ "Longitude" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep Stages",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "alias": "Deep Sleep",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "deepSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Light Sleep",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "lightSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "REM Sleep",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "remSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "awakeSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Sleep Score",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Sleep Score",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "sleepScore" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Daily Intensity Minutes",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "alias": "Moderate Intensity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "moderateIntensityMinutes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* 60" ], "type": "math" }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Vigorous Intensity",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "vigorousIntensityMinutes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* 60" ], "type": "math" }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Daily Activity Overview",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 171 },
   "targets": [
    {
     "alias": "Sleeping",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sleepingSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Sedentary",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sedentarySeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Active",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "activeSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Highly Active",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highlyActiveSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Body Battery overview",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Charged",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bodyBatteryChargedValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Drained",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bodyBatteryDrainedValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Body Battery Level Change",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 171 },
   "targets": [
    {
     "alias": "bb_low",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bodyBatteryLowestValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "bb_high",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bodyBatteryHighestValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Stress overview",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "alias": "Low Stress duration",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "lowStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Rest stress duration",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "restStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Medium stress duration",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "mediumStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Uncategorized stress duration",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "uncategorizedStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "High stress duration",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Average Sleep trends",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Deep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "deepSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Light",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lightSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "REM",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "remSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "awakeSleepSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "HR Range (Max-Min)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 182 },
   "targets": [
    {
     "alias": "hr_low",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "minHeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "hr_high",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "maxHeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Month at a Glance (Daily Average)",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 196 },
   "targets": [
    {
     "alias": "Resting HR",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "restingHeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "High Stress Duration",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "highStressDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Active time",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "activeSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Body Battery (Highest)",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "bodyBatteryHighestValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Total Steps",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "totalSteps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "SpO2",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "averageSpo2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Sleep Score",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepSummary",
     "select": [
      [
       { "params": [ "sleepScore" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "Total Sleep",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DailyStats",
     "select": [
      [
       { "params": [ "sleepingSeconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    },
    {
     "alias": "HRV",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HRV_Intraday",
     "select": [
      [
       { "params": [ "hrvValue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Month at a Glance (Intraday)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 207 },
   "targets": [
    {
     "alias": "Band Wearing",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "HeartRateIntraday",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "HR Zones",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HeartRateIntraday",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    },
    {
     "alias": "Body Battery",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BodyBatteryIntraday",
     "select": [
      [
       { "params": [ "BodyBatteryLevel" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    },
    {
     "alias": "Stress Level",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StressIntraday",
     "select": [
      [
       { "params": [ "stressLevel" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    },
    {
     "alias": "Steps Taken",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StepsIntraday",
     "select": [
      [
       { "params": [ "StepsCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HR Histogram Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 215 },
   "targets": [
    {
     "alias": "Heart Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HeartRateIntraday",
     "select": [
      [
       { "params": [ "HeartRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hourly walk heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 223 },
   "targets": [
    {
     "alias": "Hourly Steps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StepsIntraday",
     "select": [
      [
       { "params": [ "StepsCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  },
  {
   "title": "Sleep Regularity",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 223 },
   "targets": [
    {
     "alias": "Sleep Regularity",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "SleepIntraday",
     "query": "SELECT median(\"level\") FROM \"Sleep Levels\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "SleepStageLevel" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tz": "$TimeZone"
    }
   ]
  }
 ]
}